mariadb: hard disable otherwise automagic boost
It's needed for the oqgraph storage engine. The missing dep on
boost prevented me from installing it on multibuild:

/var/tmp/paludis/build/dev-db-mariadb-5.5.33a-r1/work/mariadb-5.5.33a/storage/oqgraph/graphcore.cc:578:35:   required from here
/usr/include/boost/graph/named_graph.hpp:318:3: error: invalid application of 'sizeof' to incomplete type 'boost::STATIC_ASSERTION_FAILURE<false>'

Change-Id: I9b591f7c13cccdfcb426c9e17e5a7f71ffc944d0